import { NextResponse } from "next/server";
import { Resend } from "resend";

// Initialize Resend with the provided API key (fallback allowed for out-of-the-box Vercel support)
const resend = new Resend(process.env.RESEND_API_KEY || "re_JNq1qdmj_36umXKPYnyHiFFY68AFxfxqp");

export async function POST(req: Request) {
  try {
    const { fullName, mobileNumber, emailAddress, serviceRequired, message } = await req.json();

    // Input Validations
    if (!fullName || !emailAddress || !mobileNumber || !serviceRequired || !message) {
      return NextResponse.json(
        { error: "Missing required contact form fields." },
        { status: 400 }
      );
    }

    const targetRecipient = "yaswanth777ys@gmail.com";

    // Trigger Resend API call
    // Note: Resend's default onboarding@resend.dev is used because it allows sending to the registered account email (yaswanth777ys@gmail.com) immediately.
    const { data, error } = await resend.emails.send({
      from: "SY Media Client <onboarding@resend.dev>",
      to: targetRecipient,
      replyTo: emailAddress, // Allows hitting "Reply" in your email client to talk directly to the customer
      subject: `[SY Media] Service Request: ${serviceRequired}`,
      html: `
        <div style="background-color: #0F0F0F; color: #FFFFFF; font-family: 'Poppins', Arial, sans-serif; padding: 40px; border-radius: 16px; max-width: 600px; margin: auto; border: 1px solid rgba(212, 175, 55, 0.15);">
          <!-- Header -->
          <div style="text-align: center; border-bottom: 1px solid rgba(255,255,255,0.08); padding-bottom: 20px; margin-bottom: 30px;">
            <h2 style="color: #D4AF37; font-size: 24px; font-weight: bold; letter-spacing: 2px; margin: 0;">SY MEDIA</h2>
            <p style="color: #9CA3AF; font-size: 12px; text-transform: uppercase; letter-spacing: 1px; margin-top: 5px;">Luxury Event Consultation Request</p>
          </div>
          
          <!-- Content Body -->
          <div style="font-size: 14px; line-height: 1.6;">
            <p style="color: #9CA3AF; margin-bottom: 25px;">You have received a new consultation request from the website form. Details are shown below:</p>
            
            <!-- Details Grid -->
            <table style="width: 100%; border-collapse: collapse; margin-bottom: 30px;">
              <tr>
                <td style="padding: 10px 0; border-bottom: 1px solid rgba(255,255,255,0.04); color: #9CA3AF; font-weight: bold; width: 35%;">Client Name:</td>
                <td style="padding: 10px 0; border-bottom: 1px solid rgba(255,255,255,0.04); color: #FFFFFF; font-weight: 500;">${fullName}</td>
              </tr>
              <tr>
                <td style="padding: 10px 0; border-bottom: 1px solid rgba(255,255,255,0.04); color: #9CA3AF; font-weight: bold;">Mobile Number:</td>
                <td style="padding: 10px 0; border-bottom: 1px solid rgba(255,255,255,0.04); color: #FFFFFF; font-weight: 500;">
                  <a href="tel:${mobileNumber}" style="color: #D4AF37; text-decoration: none;">${mobileNumber}</a>
                </td>
              </tr>
              <tr>
                <td style="padding: 10px 0; border-bottom: 1px solid rgba(255,255,255,0.04); color: #9CA3AF; font-weight: bold;">Email Address:</td>
                <td style="padding: 10px 0; border-bottom: 1px solid rgba(255,255,255,0.04); color: #FFFFFF; font-weight: 500;">
                  <a href="mailto:${emailAddress}" style="color: #D4AF37; text-decoration: none;">${emailAddress}</a>
                </td>
              </tr>
              <tr>
                <td style="padding: 10px 0; border-bottom: 1px solid rgba(255,255,255,0.04); color: #9CA3AF; font-weight: bold;">Service Requested:</td>
                <td style="padding: 10px 0; border-bottom: 1px solid rgba(255,255,255,0.04); color: #D4AF37; font-weight: bold; font-size: 15px;">${serviceRequired}</td>
              </tr>
            </table>
            
            <!-- Message Block -->
            <div style="background-color: #181818; border: 1px solid rgba(255,255,255,0.05); padding: 20px; border-radius: 12px; margin-top: 20px;">
              <h4 style="color: #FFFFFF; margin-top: 0; margin-bottom: 10px; font-size: 13px; text-transform: uppercase; letter-spacing: 1px; border-bottom: 1px solid rgba(255,255,255,0.05); padding-bottom: 8px;">Message Details</h4>
              <p style="color: #E5E7EB; margin: 0; font-size: 13.5px; white-space: pre-wrap;">${message}</p>
            </div>
          </div>
          
          <!-- Footer -->
          <div style="text-align: center; border-top: 1px solid rgba(255,255,255,0.08); padding-top: 20px; margin-top: 30px; color: #9CA3AF; font-size: 11px;">
            <p style="margin: 0;">This email was automatically generated by your SY Media contact portal via Resend.</p>
            <p style="margin: 5px 0 0 0;">To reply directly to this client, simply click <strong>Reply</strong> in your email program.</p>
          </div>
        </div>
      `,
    });

    if (error) {
      console.error("Resend API response error:", error);
      return NextResponse.json({ error: error.message }, { status: 400 });
    }

    return NextResponse.json({
      success: true,
      message: "Your request has been successfully dispatched to our team.",
    });
  } catch (error: any) {
    console.error("Resend catch error in API route:", error);
    return NextResponse.json(
      { error: "Server error occurred while dispatching email notification via Resend." },
      { status: 500 }
    );
  }
}
